apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-backend
  namespace: default
  labels:
    app: shop-backend
    backstage.io/kubernetes-id: shop-backend
spec:
  selector:
    matchLabels:
      app: shop-backend
  template:
    metadata:
      labels:
        app: shop-backend
        backstage.io/kubernetes-id: shop-backend
    spec:
      containers:
        - name: shop-backend
          image: nginx:alpine
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: shop-backend
  namespace: default
  labels:
    app: shop-backend
    backstage.io/kubernetes-id: shop-backend
spec:
  selector:
    app: shop-backend
  ports:
    - port: 8888
      targetPort: 80